language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - yarn test && yarn run build
after_success:
  - yarn run report-coverage
  - yarn run deploy-docs
